name: Deploy and Start Application

on:
  push:
    branches:
      - main

jobs:
  deploy_and_start:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Install Server Dependencies
        run: npm install --production

      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "build/"
          target: "/var/www/html/"
          strip_components: 1

      - name: Start React Application
        run: |
          cd /path/to/your/server
          # Start the React application
          npm start
